name: Hello world 
on: 
  push:
  workflow_dispatch:

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps: 
      - name: Salutations
        run: echo "Hello world"
      - name: Download code
        uses: actions/checkout@v4
      - name: Where 
        run: pwd
      - name: List
        run: ls -la
      - name: Install node
        uses: actions/setup-node@v4
      - name: Verify node 
        run: node --version
      - name: See npm
        run: npm init -y