name: Hello world 
on: 
  push:
  workflow_dispatch:

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps: 
      - name: Salutations
        run: echo "Hello world"
      - name: Download code
        uses: actions/checkout@v4
      - name: Where 
        uses: pwd
      - name: List
        uses: ls -la